Homework 5: Data Transformation, Exploration, and Plotting
================
Robert LaBean

Code to open documention about flights.

``` r
?nycflights13::flights
```

    ## starting httpd help server ... done

Using the glimpse function to look at the data inside flights.

``` r
glimpse(flights)
```

    ## Rows: 336,776
    ## Columns: 19
    ## $ year           <int> 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013...
    ## $ month          <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
    ## $ day            <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
    ## $ dep_time       <int> 517, 533, 542, 544, 554, 554, 555, 557, 557, 558, 55...
    ## $ sched_dep_time <int> 515, 529, 540, 545, 600, 558, 600, 600, 600, 600, 60...
    ## $ dep_delay      <dbl> 2, 4, 2, -1, -6, -4, -5, -3, -3, -2, -2, -2, -2, -2,...
    ## $ arr_time       <int> 830, 850, 923, 1004, 812, 740, 913, 709, 838, 753, 8...
    ## $ sched_arr_time <int> 819, 830, 850, 1022, 837, 728, 854, 723, 846, 745, 8...
    ## $ arr_delay      <dbl> 11, 20, 33, -18, -25, 12, 19, -14, -8, 8, -2, -3, 7,...
    ## $ carrier        <chr> "UA", "UA", "AA", "B6", "DL", "UA", "B6", "EV", "B6"...
    ## $ flight         <int> 1545, 1714, 1141, 725, 461, 1696, 507, 5708, 79, 301...
    ## $ tailnum        <chr> "N14228", "N24211", "N619AA", "N804JB", "N668DN", "N...
    ## $ origin         <chr> "EWR", "LGA", "JFK", "JFK", "LGA", "EWR", "EWR", "LG...
    ## $ dest           <chr> "IAH", "IAH", "MIA", "BQN", "ATL", "ORD", "FLL", "IA...
    ## $ air_time       <dbl> 227, 227, 160, 183, 116, 150, 158, 53, 140, 138, 149...
    ## $ distance       <dbl> 1400, 1416, 1089, 1576, 762, 719, 1065, 229, 944, 73...
    ## $ hour           <dbl> 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6...
    ## $ minute         <dbl> 15, 29, 40, 45, 0, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59...
    ## $ time_hour      <dttm> 2013-01-01 05:00:00, 2013-01-01 05:00:00, 2013-01-0...

There are 336776 rows in flights and 19 columns.

Create a dataframe of only flights that departed 2 hours late or more.

``` r
late_flights <- filter(flights, dep_delay >=2) 
percent_late_flights <-
  signif((nrow(late_flights)/nrow(flights))*100,3)
percent_late_flights # This is the percentage of flights that departed 2 hours late or later,
```

    ## [1] 35.7

``` r
# rounded to 3 significant figures/
```

35.7% of flights in 2013 were 2 hours late or more.

Create a column that contains combined airline and flight number (e.g.,
“UA5401”).

``` r
airline_num <- mutate(flights, flightnum = paste0(flights$carrier, flights$flight))
airline_num # This column is carrier + flight number
```

    ## # A tibble: 336,776 x 20
    ##     year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
    ##    <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
    ##  1  2013     1     1      517            515         2      830            819
    ##  2  2013     1     1      533            529         4      850            830
    ##  3  2013     1     1      542            540         2      923            850
    ##  4  2013     1     1      544            545        -1     1004           1022
    ##  5  2013     1     1      554            600        -6      812            837
    ##  6  2013     1     1      554            558        -4      740            728
    ##  7  2013     1     1      555            600        -5      913            854
    ##  8  2013     1     1      557            600        -3      709            723
    ##  9  2013     1     1      557            600        -3      838            846
    ## 10  2013     1     1      558            600        -2      753            745
    ## # ... with 336,766 more rows, and 12 more variables: arr_delay <dbl>,
    ## #   carrier <chr>, flight <int>, tailnum <chr>, origin <chr>, dest <chr>,
    ## #   air_time <dbl>, distance <dbl>, hour <dbl>, minute <dbl>, time_hour <dttm>,
    ## #   flightnum <chr>

Use group\_by(), summarise(), and n() to make a data frame showing how
many flights each aircraft (tail\_num()) flew for each carrier
throughout the entire data set.

``` r
num_flight_tot <- flights %>%
  group_by(carrier, tailnum)%>%
  summarise(numflights = n())
```

    ## `summarise()` regrouping output by 'carrier' (override with `.groups` argument)

``` r
num_flight_tot # This column is the number of flights each tail number has flown for entire set of data
```

    ## # A tibble: 4,067 x 3
    ## # Groups:   carrier [16]
    ##    carrier tailnum numflights
    ##    <chr>   <chr>        <int>
    ##  1 9E      N146PQ           8
    ##  2 9E      N153PQ           5
    ##  3 9E      N161PQ           3
    ##  4 9E      N162PQ           2
    ##  5 9E      N170PQ           7
    ##  6 9E      N176PQ           7
    ##  7 9E      N181PQ           4
    ##  8 9E      N187PQ           5
    ##  9 9E      N197PQ           2
    ## 10 9E      N200PQ           7
    ## # ... with 4,057 more rows
